PullRq: Req 02 Atendido y la mezcla de las correcciones ya liberadas en la v1.0.1
dvdSanchez/rpRemoto01 pull request #2
Opened 2024-07-31 14:22 UTC by abstraeDiego

Requerimientos atendidos
Req 02: Que permita sumar más de dos fracciones
Fallas integradas: 
F01: Cuando se proporciona una fracción con denominador cero, la aplicación deja de funcionar
F02: Que permita identificar de alguna manera que fracción se va capturando

2024-07-31 14:27 UTC, abstraeDiego commented
Equipo, les notifico que he terminado de atender el Req 02 y la integración con la v1.0.1

Solicito se validen los cambios y si así lo consideran autorizar para q se integren a producción

2024-08-07 04:10 UTC, abstraeDiego commented
Agregue el Req 01: Que muestre la fracción como una fracción mixta

2024-08-07 05:04 UTC, JosueAbstrae requested changes
Por favor, apoyar lo que se le indicó

2024-08-07 05:04 UTC, JosueAbstrae commented on src/com/abstrae/calculadora/vista/FraccionGui.java
Los métodos Linea 11: solicitaFraccion(String pIdFrac) y Linea 32: solicitaFraccion() son esencialmente lo mismo
Veo un riesgo, si hay un cambio en el comportamiento de uno de los métodos es posible que no se actualicen los dos. Solicito que se mitigue ese riesgo

2024-08-07 05:24 UTC, abstraeDiego reviewed
¡Listo! Mejora atendida

2024-08-07 05:26 UTC, JosueAbstrae approved these changes
De acuerdo!

2024-08-07 05:28 UTC, JosueAbstrae commented
Autorizo que se haga el merge en el main.

2024-08-07 05:30 UTC, merged